version: '2.0'

services:
  # PostgreSQL database
  db:
    image: postgres:10
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:3.2.11
    hostname: redis
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.0
    environment:
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_VHOST=host0
    ports:
      - "5672:5672"
      - "15672:15672"

  # Admin Panel Service
  admin-panel:
    build:
      context: admin_panel
      dockerfile: Dockerfile
    hostname: web
    environment:
      - COORDINATE_GENERATE_API_URL=http://api:8085/coordinates
      - IMAGE_GENERATE_API_URL=http://highcharts:8080
      - MEDIA_ROOT=/opt/app/media
    command: ./run_web.sh
    links:
      - db
      - rabbit
      - redis
      - api
      - highcharts
    depends_on:
      - db
    volumes:
      - ./admin_panel/media:/opt/app/media
    ports:
      - "8000:8000"
  #
  api:
    build:
      context: coordinate_generator
      dockerfile: Dockerfile
    hostname: api
#    command: ./run_api.sh
    ports:
      - "8085:8085"
    links:
      - db
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: admin_panel
      dockerfile: Dockerfile
    command: ./run_celery.sh
    environment:
      - COORDINATE_GENERATE_API_URL=http://api:8085/coordinates
      - IMAGE_GENERATE_API_URL=http://highcharts:8080
      - MEDIA_ROOT=/opt/app/media
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
    volumes:
      - ./admin_panel/media:/opt/app/media

  highcharts:
    hostname: highcharts
    image: onsdigital/highcharts-export-node
    ports:
      - "8080:8080"
